spring:
  application:
    name: ACTIVITYSERVICE

  data:
    mongodb:
      uri: mongodb://localhost:27017/aiactivityfitness

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

server:
  port: 8082

# ðŸ”¹ Custom app config (NOT under spring.kafka to avoid breaking auto-config)
topic:
  activity: activity-topic

# Optional: if you want to override instead of hardcoding in config
spring:
  kafka:
    bootstrap-servers: localhost:9092