spring:
  application:
    name: AISERVICE

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: activity-processor-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.fitness.aiservice.model.Activity
        spring.json.trusted.packages: com.fitness.aiservice.model
        spring.json.use.type.headers: false

topic:
  activity: activity-topic

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

server:
  port: 8083