spring:
  application:
    name: AISERVICE

  data:
    mongodb:
      uri: mongodb://localhost:27017/airecomendationfitness
      database: airecomendationfitness

  kafka:
    bootstrap-servers: localhost:9092

    topic:
      name: activity-topic   # REQUIRED

    consumer:
      group-id: activity-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

server:
  port: 8083